/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Parte_2;


import static java.lang.Thread.sleep;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author blanf
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    Campamento camp;
    Detener deten;
    Monitor mon;
    Child c;
    ArrayList<Child> niños = new ArrayList <Child>();   //Lista dónde guardaremos niños creados
    public Interfaz() {
        initComponents();
        int contActChild = 0, contActMon = 0;   //Se inicializan los contadores de actividades de los niños y monitores
        deten = new Detener();
        camp = new Campamento(50, colaEsperaTirolina, colaEsperaSoga, niñosMerendando,numeroUsosTir,bandejasLimpias,bandejasSucias, numActividades, deten);
        
        //Bucle para crear los monitores
        for(int i = 1; i<=4; i++)
        {
            String n1 = String.valueOf(i);      //Convierte entero en string
            mon = new Monitor('M' + n1, camp, contActMon,deten);    //Creo monitor
            mon.start();    //Empieza ejecución de monitor
        }
        //Crea hilo anónimo en el que crearé todos los hilos child que componen el sistema
        new Thread (new Runnable()
        {
            public void run()
            {
                //Bucle para crear los hilos niños
                for(int i = 1; i <= 100; i++)
                {
                    String n2 = String.valueOf(i);  //Convierte valor de i en un string 
                    c = new Child('N' + n2, camp, contActChild,deten);  //Creo hilo niño
                    c.start();
                    niños.add(c);   //Añade niño creado a la lista
                    try
                    {
                    sleep(1000 + (int)(2000*Math.random()));    //Niños se crean cada 1 - 3 segundos
                    } catch (InterruptedException e){ }
                }
            }   
        }).start();    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloCampamento = new javax.swing.JLabel();
        tituloTirolina = new javax.swing.JLabel();
        tituloColaEsperaTirolina = new javax.swing.JLabel();
        tituloNumeroUsosTirol = new javax.swing.JLabel();
        colaEsperaTirolina = new javax.swing.JTextField();
        numeroUsosTir = new javax.swing.JTextField();
        consultarColaEsperaTir = new javax.swing.JButton();
        consultarNumeroUsosTir = new javax.swing.JButton();
        TituloMerienda = new javax.swing.JLabel();
        TituloMerendando = new javax.swing.JLabel();
        tituloBandeSuc = new javax.swing.JLabel();
        tituloBandLimpias = new javax.swing.JLabel();
        niñosMerendando = new javax.swing.JTextField();
        bandejasSucias = new javax.swing.JTextField();
        bandejasLimpias = new javax.swing.JTextField();
        consultarNiñosMer = new javax.swing.JButton();
        consultarBandejasSuc = new javax.swing.JButton();
        consultarBandeLimp = new javax.swing.JButton();
        tituloSoga = new javax.swing.JLabel();
        tituloColaEsperaSoga = new javax.swing.JLabel();
        colaEsperaSoga = new javax.swing.JTextField();
        tituloActividades = new javax.swing.JLabel();
        consultarColaEsperaSoga = new javax.swing.JButton();
        tituloIdNiño = new javax.swing.JLabel();
        idNiño = new javax.swing.JTextField();
        consultarId = new javax.swing.JButton();
        tituloNumActs = new javax.swing.JLabel();
        numActividades = new javax.swing.JTextField();
        errorId = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        tituloCampamento.setText("Control del campamento");

        tituloTirolina.setText("Tirolina");

        tituloColaEsperaTirolina.setText("Cola de espera");

        tituloNumeroUsosTirol.setText("Número de usos:");

        consultarColaEsperaTir.setText("Consultar");
        consultarColaEsperaTir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarColaEsperaTirActionPerformed(evt);
            }
        });

        consultarNumeroUsosTir.setText("Consultar");
        consultarNumeroUsosTir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarNumeroUsosTirActionPerformed(evt);
            }
        });

        TituloMerienda.setText("Merienda");

        TituloMerendando.setText("Niños merendando:");

        tituloBandeSuc.setText("Bandejas sucias:");

        tituloBandLimpias.setText("Bandejas limpias:");

        consultarNiñosMer.setText("Consultar");
        consultarNiñosMer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarNiñosMerActionPerformed(evt);
            }
        });

        consultarBandejasSuc.setText("Consultar");
        consultarBandejasSuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarBandejasSucActionPerformed(evt);
            }
        });

        consultarBandeLimp.setText("Consultar");
        consultarBandeLimp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarBandeLimpActionPerformed(evt);
            }
        });

        tituloSoga.setText("Soga");

        tituloColaEsperaSoga.setText("Cola de espera:");

        tituloActividades.setText("Actividades");

        consultarColaEsperaSoga.setText("Consultar");
        consultarColaEsperaSoga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarColaEsperaSogaActionPerformed(evt);
            }
        });

        tituloIdNiño.setText("Id niño : ");

        idNiño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idNiñoActionPerformed(evt);
            }
        });

        consultarId.setText("Consultar");
        consultarId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarIdActionPerformed(evt);
            }
        });

        tituloNumActs.setText("Número de actividades:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(364, 364, 364)
                .addComponent(tituloCampamento, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tituloColaEsperaTirolina, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tituloNumeroUsosTirol))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(colaEsperaTirolina)
                                    .addComponent(numeroUsosTir, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(tituloColaEsperaSoga, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tituloSoga, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(colaEsperaSoga, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(consultarColaEsperaTir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(consultarNumeroUsosTir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(consultarColaEsperaSoga))
                        .addGap(181, 181, 181)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tituloNumActs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numActividades, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tituloBandLimpias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TituloMerendando, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tituloBandeSuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bandejasSucias)
                                    .addComponent(bandejasLimpias)
                                    .addComponent(niñosMerendando)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(tituloIdNiño, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tituloActividades, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(idNiño, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(consultarNiñosMer, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                            .addComponent(consultarBandejasSuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(consultarBandeLimp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(consultarId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(errorId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(43, 43, 43))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(tituloTirolina, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TituloMerienda, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(173, 173, 173))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(tituloCampamento, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloTirolina, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TituloMerienda))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloColaEsperaTirolina)
                    .addComponent(colaEsperaTirolina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultarColaEsperaTir)
                    .addComponent(TituloMerendando)
                    .addComponent(niñosMerendando, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultarNiñosMer))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloNumeroUsosTirol, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numeroUsosTir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultarNumeroUsosTir)
                    .addComponent(tituloBandeSuc)
                    .addComponent(bandejasSucias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultarBandejasSuc))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloBandLimpias)
                    .addComponent(bandejasLimpias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultarBandeLimp))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloActividades)
                    .addComponent(tituloSoga))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(colaEsperaSoga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tituloColaEsperaSoga)
                    .addComponent(consultarColaEsperaSoga)
                    .addComponent(tituloIdNiño)
                    .addComponent(idNiño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(consultarId))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tituloNumActs)
                            .addComponent(numActividades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(errorId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultarColaEsperaTirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarColaEsperaTirActionPerformed
        camp.consultarColaTirolina();   //Llama a función consultar cola de espera de la tirolina
    }//GEN-LAST:event_consultarColaEsperaTirActionPerformed

    private void consultarColaEsperaSogaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarColaEsperaSogaActionPerformed
        camp.consultarColaSoga();   //Llama a función consultar número de niños en cola de la soga
    }//GEN-LAST:event_consultarColaEsperaSogaActionPerformed

    private void consultarNiñosMerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarNiñosMerActionPerformed
        camp.consultarMerendero();  //Lama a función de consulta de número de niños en el merendero
    }//GEN-LAST:event_consultarNiñosMerActionPerformed

    private void consultarBandejasSucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarBandejasSucActionPerformed
        camp.consultarBandejasSucias(); //Llama a función para consultar número de bandejas sucias en merendero
    }//GEN-LAST:event_consultarBandejasSucActionPerformed

    private void consultarBandeLimpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarBandeLimpActionPerformed
        camp.consultarBandejasLimpias(); //Llama a función para consultar número de bandejas limpias
    }//GEN-LAST:event_consultarBandeLimpActionPerformed

    private void consultarNumeroUsosTirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarNumeroUsosTirActionPerformed
        camp.consultarVecesTirolina();  //Llama a función para consultar número de veces se ha llevado a cabo actividad tirolina
    }//GEN-LAST:event_consultarNumeroUsosTirActionPerformed

    private void idNiñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idNiñoActionPerformed
        
    }//GEN-LAST:event_idNiñoActionPerformed

    private void consultarIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarIdActionPerformed
        
        String id;
        //id = " ";
        if(!idNiño.getText().isEmpty()) //Si el espacio dónde que hay introducir id del niño a consultar no esta vacio
        {
            errorId.setText(" "); //Quita aviso
            id = idNiño.getText();  //Recoge identificador del niño especificado
            for(int i = 0; i < niños.size(); i++)   //Bucle recorre niños creados paar determianar de que niño es el id que buscamos
            {
                if(niños.get(i).getCId().equals(id)) //Comprueba si el id corresponde a niño
                {
                    camp.consultarNiño(niños.get(i));   //Llama a función para consultar numero de actividades realizadas por niño especifico
                }
            }
        }
        else //Si espacio esta vacio
        {
            errorId.setText("Introduce id");    //Indica a usuario que introduzca id
        }
    }//GEN-LAST:event_consultarIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TituloMerendando;
    private javax.swing.JLabel TituloMerienda;
    private javax.swing.JTextField bandejasLimpias;
    private javax.swing.JTextField bandejasSucias;
    private javax.swing.JTextField colaEsperaSoga;
    private javax.swing.JTextField colaEsperaTirolina;
    private javax.swing.JButton consultarBandeLimp;
    private javax.swing.JButton consultarBandejasSuc;
    private javax.swing.JButton consultarColaEsperaSoga;
    private javax.swing.JButton consultarColaEsperaTir;
    private javax.swing.JButton consultarId;
    private javax.swing.JButton consultarNiñosMer;
    private javax.swing.JButton consultarNumeroUsosTir;
    private javax.swing.JLabel errorId;
    private javax.swing.JTextField idNiño;
    private javax.swing.JTextField niñosMerendando;
    private javax.swing.JTextField numActividades;
    private javax.swing.JTextField numeroUsosTir;
    private javax.swing.JLabel tituloActividades;
    private javax.swing.JLabel tituloBandLimpias;
    private javax.swing.JLabel tituloBandeSuc;
    private javax.swing.JLabel tituloCampamento;
    private javax.swing.JLabel tituloColaEsperaSoga;
    private javax.swing.JLabel tituloColaEsperaTirolina;
    private javax.swing.JLabel tituloIdNiño;
    private javax.swing.JLabel tituloNumActs;
    private javax.swing.JLabel tituloNumeroUsosTirol;
    private javax.swing.JLabel tituloSoga;
    private javax.swing.JLabel tituloTirolina;
    // End of variables declaration//GEN-END:variables
}
