/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Parte_1;

/**
 *
 * @author blanf
 */
public class Interfaz extends javax.swing.JFrame {
    /*Inicializo variables*/
    Campamento camp;
    Monitor mon;
    Detener deten;
    Child c;
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        AtomicInteger contActChild = new AtomicInteger(0);
        AtomicInteger contActMon = new AtomicInteger(0);

        camp=new Campamento(50,colaEsperaIzq,colaEsperaDer,colaEsperaTirolina,colaEntradaMerendero,dentro,monitorTir,monitoresMerendero,monitoresZC,monitorSoga,colaEntradaMerendero,colaEsperaTirolina,hilosEntran,childMerendando,bandejasLimpias,bandejasSucias,childZC,childPreparacion,childEnTirolina,childEnFinal,equipoA,equipoB);
        deten = new Detener();
        
        //Bucle para crear los monitores
        for(int i = 1; i<=4; i++)
        {
            String n1 = String.valueOf(i);      //Convierte entero en string
            mon = new Monitor('M' + n1, camp, contActMon);
            mon.start();
        }
        for(int i = 1; i <= 200; i++)
                {
                    String n2 = String.valueOf(i);
                    c = new Child('N' + n2, camp, contActChild);
                    c.start();
                }
        //Crea hilo anónimo en el que crearé todos los hilos que componen el sistema
        new Thread (new Runnable()
        {
            public void run()
            {
                //Bucle para crear los hilos niños
                for(int i = 1; i <= 200; i++)
                {
                    String n2 = String.valueOf(i);
                    c = new Child('N' + n2, camp, contActChild);
                    c.start();
                }
            }   
        }).start();   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar2 = new javax.swing.JScrollBar();
        Titulo = new javax.swing.JLabel();
        TituloEntradaIzq = new javax.swing.JLabel();
        TituloEntradaDer = new javax.swing.JLabel();
        ColaEsperaIzq = new javax.swing.JTextField();
        ColaEsperaDer = new javax.swing.JTextField();
        TituloCamp = new javax.swing.JLabel();
        TituloSoga = new javax.swing.JLabel();
        TituloTirolina = new javax.swing.JLabel();
        HilosEntran = new javax.swing.JTextField();
        ColaEsperaTirolina = new javax.swing.JTextField();
        TituloMonitorSoga = new javax.swing.JLabel();
        TituloequipoA = new javax.swing.JLabel();
        TituloEquipoB = new javax.swing.JLabel();
        EquipoA = new javax.swing.JScrollPane();
        EquipoB = new javax.swing.JScrollPane();
        MonitorTir = new javax.swing.JTextField();
        TituloMonitosTir = new javax.swing.JLabel();
        TituloPreparacion = new javax.swing.JLabel();
        ChildPreparacion = new javax.swing.JTextField();
        TituloEnTir = new javax.swing.JLabel();
        ChildEnTirolina = new javax.swing.JTextField();
        TituloFinalizado = new javax.swing.JLabel();
        ChildEnFinal = new javax.swing.JTextField();
        MonitorSoga = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TituloMonitorZC = new javax.swing.JLabel();
        TituloChildZC = new javax.swing.JLabel();
        MonitoresZC = new javax.swing.JTextField();
        ChildZC = new javax.swing.JTextField();
        TituloMerendero = new javax.swing.JLabel();
        ColaEntradaMonitores = new javax.swing.JTextField();
        TituloBandejSucias = new javax.swing.JLabel();
        TituloBandejLimp = new javax.swing.JLabel();
        TituloMonitorMeren = new javax.swing.JLabel();
        BandejasSucias = new javax.swing.JTextField();
        BandejasLimpias = new javax.swing.JTextField();
        ChildMerendando = new javax.swing.JTextField();
        MonitoresMerendero = new javax.swing.JTextField();
        BotonPausar = new javax.swing.JButton();
        BotonReanudar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Titulo.setText("Entrada al campamento");

        TituloEntradaIzq.setText("Puerta Izquierda");

        TituloEntradaDer.setText("Puerta derecha");

        ColaEsperaIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColaEsperaIzqActionPerformed(evt);
            }
        });

        ColaEsperaDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColaEsperaDerActionPerformed(evt);
            }
        });

        TituloCamp.setText("Campamento");

        TituloSoga.setText("Soga");

        TituloTirolina.setText("Tirolina");

        ColaEsperaTirolina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColaEsperaTirolinaActionPerformed(evt);
            }
        });

        TituloMonitorSoga.setText("Monitor");

        TituloequipoA.setText("Equipo A");

        TituloEquipoB.setText("Equipo B");

        MonitorTir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonitorTirActionPerformed(evt);
            }
        });

        TituloMonitosTir.setText("Monitor");

        TituloPreparacion.setText("Preparacion");

        TituloEnTir.setText("Tirolina");

        TituloFinalizado.setText("Finalizacion");

        jLabel1.setText("Zona Comun");

        TituloMonitorZC.setText("Monitores");

        TituloChildZC.setText("Child");

        TituloMerendero.setText("Merendero");

        TituloBandejSucias.setText("Bandejas Sucias");

        TituloBandejLimp.setText("Bandejas Limpias");

        TituloMonitorMeren.setText("Monitores");

        BotonPausar.setText("Pausar");
        BotonPausar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPausarActionPerformed(evt);
            }
        });

        BotonReanudar.setText("Reanudar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(TituloEntradaIzq, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TituloEntradaDer, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133))
            .addGroup(layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(TituloSoga, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TituloTirolina, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(201, 201, 201))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TituloCamp, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(425, 425, 425))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(391, 391, 391)
                        .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(434, 434, 434)
                        .addComponent(TituloMerendero, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ColaEntradaMonitores)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(HilosEntran)
                            .addComponent(ColaEsperaIzq))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(MonitorTir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TituloMonitosTir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ChildPreparacion, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TituloPreparacion, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TituloEnTir)
                                    .addComponent(ChildEnTirolina, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TituloFinalizado, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ChildEnFinal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(ColaEsperaTirolina, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ColaEsperaDer, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(42, 42, 42))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TituloMonitorZC, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(MonitoresZC))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TituloMonitorSoga, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MonitorSoga, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TituloequipoA, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EquipoA, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EquipoB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TituloEquipoB, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TituloChildZC, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ChildZC)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(MonitoresMerendero, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TituloBandejSucias, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BandejasSucias, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TituloMonitorMeren, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(51, 51, 51)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TituloBandejLimp, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                    .addComponent(BandejasLimpias))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(ChildMerendando, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BotonPausar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(BotonReanudar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 20, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TituloEntradaIzq, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TituloEntradaDer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ColaEsperaIzq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ColaEsperaDer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(TituloCamp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TituloTirolina, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TituloSoga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HilosEntran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ColaEsperaTirolina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TituloPreparacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TituloMonitorSoga)
                        .addComponent(TituloequipoA)
                        .addComponent(TituloEquipoB)
                        .addComponent(TituloFinalizado)
                        .addComponent(TituloEnTir)
                        .addComponent(TituloMonitosTir)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EquipoA, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EquipoB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(MonitorTir, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ChildPreparacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ChildEnTirolina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ChildEnFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(MonitorSoga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TituloMonitorZC)
                    .addComponent(TituloChildZC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MonitoresZC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChildZC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(TituloMerendero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ColaEntradaMonitores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TituloBandejSucias)
                    .addComponent(TituloBandejLimp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BandejasSucias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BandejasLimpias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TituloMonitorMeren))
                    .addComponent(ChildMerendando))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MonitoresMerendero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonPausar)
                    .addComponent(BotonReanudar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ColaEsperaIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColaEsperaIzqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ColaEsperaIzqActionPerformed

    private void ColaEsperaDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColaEsperaDerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ColaEsperaDerActionPerformed

    private void ColaEsperaTirolinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColaEsperaTirolinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ColaEsperaTirolinaActionPerformed

    private void MonitorTirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonitorTirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MonitorTirActionPerformed

    private void BotonPausarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPausarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonPausarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not availjTextField1tay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BandejasLimpias;
    private javax.swing.JTextField BandejasSucias;
    private javax.swing.JButton BotonPausar;
    private javax.swing.JButton BotonReanudar;
    private javax.swing.JTextField ChildEnFinal;
    private javax.swing.JTextField ChildEnTirolina;
    private javax.swing.JTextField ChildMerendando;
    private javax.swing.JTextField ChildPreparacion;
    private javax.swing.JTextField ChildZC;
    private javax.swing.JTextField ColaEntradaMonitores;
    private javax.swing.JTextField ColaEsperaDer;
    private javax.swing.JTextField ColaEsperaIzq;
    private javax.swing.JTextField ColaEsperaTirolina;
    private javax.swing.JScrollPane EquipoA;
    private javax.swing.JScrollPane EquipoB;
    private javax.swing.JTextField HilosEntran;
    private javax.swing.JTextField MonitorSoga;
    private javax.swing.JTextField MonitorTir;
    private javax.swing.JTextField MonitoresMerendero;
    private javax.swing.JTextField MonitoresZC;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel TituloBandejLimp;
    private javax.swing.JLabel TituloBandejSucias;
    private javax.swing.JLabel TituloCamp;
    private javax.swing.JLabel TituloChildZC;
    private javax.swing.JLabel TituloEnTir;
    private javax.swing.JLabel TituloEntradaDer;
    private javax.swing.JLabel TituloEntradaIzq;
    private javax.swing.JLabel TituloEquipoB;
    private javax.swing.JLabel TituloFinalizado;
    private javax.swing.JLabel TituloMerendero;
    private javax.swing.JLabel TituloMonitorMeren;
    private javax.swing.JLabel TituloMonitorSoga;
    private javax.swing.JLabel TituloMonitorZC;
    private javax.swing.JLabel TituloMonitosTir;
    private javax.swing.JLabel TituloPreparacion;
    private javax.swing.JLabel TituloSoga;
    private javax.swing.JLabel TituloTirolina;
    private javax.swing.JLabel TituloequipoA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollBar jScrollBar2;
    // End of variables declaration//GEN-END:variables
}
